<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-language-background color-primary-bg">
    <div class="header-language-container container">
        <div class="row">
            <div class="col-lg-3">
                <div class="store-language-container">
                    <?php echo $this->getChildHtml('store_language') ?>
                </div>

                <?php echo $this->getChildHtml('currency_switcher') ?>
            </div>
            <div class="col-lg-9">
                <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>
            </div>
        </div>
    </div>
</div>
